print("My name is Mark")
print("I was born in June")
print ("My name is Carol")
print("November")
print("2018")
print("My favorite food is pasta")
print("My favorite music is anything I can sing to")
print("I am a gemini")
